sudo: required

language: python
python:
  - "2.7"
  - "3.4"

services:
  - docker

before_install:
  - sudo apt-get install jq
  - ./.travis/run_hawkular.sh
env:
  global:
    - PYTHONPATH=.
  matrix:
    - HAWKULAR_VERSION=latest
    - HAWKULAR_IMAGE=hawkular/hawkular-alerts

script: pytest
